#!/usr/bin/env python

import json
import os
import sys
import urllib2

def getAlbumID(url):
    return url.split("/")[-1][:5]

def getAPIResults(albumID):
    opener = urllib2.build_opener()
    opener.addheaders = [("Authorization", "Client-ID a76b0733b2ba03a")]
    return json.load(opener.open(
        "https://api.imgur.com/3/album/%s.json" % urllib2.quote(albumID)
    ))

def getImageURLs(apiResults):
    return (x["link"] for x in apiResults["data"]["images"])

if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SyntaxError("Usage: %s id" % os.path.basename(sys.argv[0]))
    print "\n".join(getImageURLs(getAPIResults(getAlbumID(sys.argv[1]))))
