#!/usr/bin/env python

import json
import os
import sys
import urllib

class imgurAlbumGet():
    def getAlbumID(self, url):
        return url.split("/")[-1][:5]

    def getAPIResults(self, albumID):
        return json.load(urllib.urlopen("http://api.imgur.com/2/album/%s.json" %
                                        urllib.quote_plus(albumID)))

    def getImageURLs(self, apiResults):
        return (x["links"]["original"] for x in apiResults["album"]["images"])

def main():
    try:
        _, albumID = sys.argv
    except ValueError:
        raise SyntaxError("Usage: %s id" % os.path.basename(sys.argv[0]))
    i = imgurAlbumGet()
    print "\n".join(i.getImageURLs(i.getAPIResults(i.getAlbumID(albumID))))

if __name__ == "__main__":
    main()
